---
- name: update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: install apt-transport-https
  apt: name=apt-transport-https state=present

- name: install htop
  apt: name=htop state=present

- name: install ufw firewall
  include: ufw.yml

- name: install pip
  apt: name=python-pip state=latest

- name: upgrade pip
  pip:
    name: pip
    state: latest

- name: install pip dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - docker-py
